In [1]:
# DOC2VEC
import sklearn
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("News Sentiment.csv")

In [3]:
data=data.drop(["IDLink","Headline","Source","Topic","PublishDate","Facebook","GooglePlus","LinkedIn","SentimentHeadline"],axis=1)

In [4]:
 data

                                                   Title  SentimentTitle
0       Obama Lays Wreath at Arlington National Cemetery        0.000000
1            A Look at the Health of the Chinese Economy        0.208333
2       Nouriel Roubini: Global Economy Not Back to 2008       -0.425210
3                              Finland GDP Expands In Q4        0.000000
4      Tourism, govt spending buoys Thai economy in J...        0.000000
...                                                  ...             ...
55927  Fidel Castro Lashes Out at Obama After Cuba Visit       -0.135417
55928  JOHN CRISP | Obama's strategic reaction to Bru...        0.236228
55929  Think Trump's 45 Percent Tariffs Are Bad? Try ...        0.025747
55930           Microsoft finally releases giant Surface        0.000000
55931                 Rays of sunshine in the US economy        0.000000

[55932 rows x 2 columns]

In [5]:
import gensim

In [6]:
import string

In [7]:
def remove_punctuation(text):
    a=''.join([i.lower() for i in text if i not in string.punctuation])
    return a

In [8]:
data["new title"]=data["Title"].apply(lambda i:remove_punctuation(i))

In [9]:
data

,Title,SentimentTitle,new title
0,Obama Lays Wreath at Arlington National Cemetery,0.000000,obama lays wreath at arlington national cemetery
1,A Look at the Health of the Chinese Economy,0.208333,a look at the health of the chinese economy
2,Nouriel Roubini: Global Economy Not Back to 2008,-0.425210,nouriel roubini global economy not back to 2008
3,Finland GDP Expands In Q4,0.000000,finland gdp expands in q4
4,"Tourism, govt spending buoys Thai economy in J...",0.000000,tourism govt spending buoys thai economy in ja...
...,...,...,...
55927,Fidel Castro Lashes Out at Obama After Cuba Visit,-0.135417,fidel castro lashes out at obama after cuba visit
55928,JOHN CRISP | Obama's strategic reaction to Bru...,0.236228,john crisp obamas strategic reaction to brussels
55929,Think Trump's 45 Percent Tariffs Are Bad? Try ...,0.025747,think trumps 45 percent tariffs are bad try ob...
55930,Microsoft finally releases giant Surface,0.000000,microsoft finally releases giant surface
55931,Rays of sunshine in the US economy,0.000000,rays of sunshine in the us economy

In [10]:
data=data.drop(["SentimentTitle"],axis=1)

In [11]:
data

,Title,new title
0,Obama Lays Wreath at Arlington National Cemetery,obama lays wreath at arlington national cemetery
1,A Look at the Health of the Chinese Economy,a look at the health of the chinese economy
2,Nouriel Roubini: Global Economy Not Back to 2008,nouriel roubini global economy not back to 2008
3,Finland GDP Expands In Q4,finland gdp expands in q4
4,"Tourism, govt spending buoys Thai economy in J...",tourism govt spending buoys thai economy in ja...
...,...,...
55927,Fidel Castro Lashes Out at Obama After Cuba Visit,fidel castro lashes out at obama after cuba visit
55928,JOHN CRISP | Obama's strategic reaction to Bru...,john crisp obamas strategic reaction to brussels
55929,Think Trump's 45 Percent Tariffs Are Bad? Try ...,think trumps 45 percent tariffs are bad try ob...
55930,Microsoft finally releases giant Surface,microsoft finally releases giant surface
55931,Rays of sunshine in the US economy,rays of sunshine in the us economy

In [12]:
pd.set_option('display.max_colwidth', 100)

In [13]:
data

,Title,new title
0,Obama Lays Wreath at Arlington National Cemetery,obama lays wreath at arlington national cemetery
1,A Look at the Health of the Chinese Economy,a look at the health of the chinese economy
2,Nouriel Roubini: Global Economy Not Back to 2008,nouriel roubini global economy not back to 2008
3,Finland GDP Expands In Q4,finland gdp expands in q4
4,"Tourism, govt spending buoys Thai economy in January",tourism govt spending buoys thai economy in january
...,...,...
55927,Fidel Castro Lashes Out at Obama After Cuba Visit,fidel castro lashes out at obama after cuba visit
55928,JOHN CRISP | Obama's strategic reaction to Brussels,john crisp obamas strategic reaction to brussels
55929,Think Trump's 45 Percent Tariffs Are Bad? Try Obama's 10000 ...,think trumps 45 percent tariffs are bad try obamas 10000
55930,Microsoft finally releases giant Surface,microsoft finally releases giant surface
55931,Rays of sunshine in the US economy,rays of sunshine in the us economy

In [14]:
import re

In [15]:
def remove_num(text):
    text=re.sub('[0-9]+', '',text )
    return text

In [16]:
data['new title']=data['new title'].apply(lambda i:remove_num(i))

In [17]:
data

,Title,new title
0,Obama Lays Wreath at Arlington National Cemetery,obama lays wreath at arlington national cemetery
1,A Look at the Health of the Chinese Economy,a look at the health of the chinese economy
2,Nouriel Roubini: Global Economy Not Back to 2008,nouriel roubini global economy not back to
3,Finland GDP Expands In Q4,finland gdp expands in q
4,"Tourism, govt spending buoys Thai economy in January",tourism govt spending buoys thai economy in january
...,...,...
55927,Fidel Castro Lashes Out at Obama After Cuba Visit,fidel castro lashes out at obama after cuba visit
55928,JOHN CRISP | Obama's strategic reaction to Brussels,john crisp obamas strategic reaction to brussels
55929,Think Trump's 45 Percent Tariffs Are Bad? Try Obama's 10000 ...,think trumps percent tariffs are bad try obamas
55930,Microsoft finally releases giant Surface,microsoft finally releases giant surface
55931,Rays of sunshine in the US economy,rays of sunshine in the us economy

In [18]:
from nltk.tokenize import word_tokenize
# from nltk.stem import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [19]:
token=[]
lemme= WordNetLemmatizer()
stop_words=stopwords.words("english")
for i in data["new title"]:
    word=word_tokenize(i)
    lemmatize=[lemme.lemmatize(i) for i in word if i not in stop_words]
    token.append(' '.join(lemmatize))

In [20]:
# def last(text):
#     for i in data["new title"]:
#         word=word_tokenize(i)
#         lemmatize=[lemme.lemmatize(i) for i in word if i not in stop_words]
#     return lemmatize

In [21]:
# data["new title"]=data["new title"].apply(lambda i:last(i))

In [22]:
# token

In [23]:
# simple preprocessing
data

,Title,new title
0,Obama Lays Wreath at Arlington National Cemetery,obama lays wreath at arlington national cemetery
1,A Look at the Health of the Chinese Economy,a look at the health of the chinese economy
2,Nouriel Roubini: Global Economy Not Back to 2008,nouriel roubini global economy not back to
3,Finland GDP Expands In Q4,finland gdp expands in q
4,"Tourism, govt spending buoys Thai economy in January",tourism govt spending buoys thai economy in january
...,...,...
55927,Fidel Castro Lashes Out at Obama After Cuba Visit,fidel castro lashes out at obama after cuba visit
55928,JOHN CRISP | Obama's strategic reaction to Brussels,john crisp obamas strategic reaction to brussels
55929,Think Trump's 45 Percent Tariffs Are Bad? Try Obama's 10000 ...,think trumps percent tariffs are bad try obamas
55930,Microsoft finally releases giant Surface,microsoft finally releases giant surface
55931,Rays of sunshine in the US economy,rays of sunshine in the us economy

In [24]:
data=data.drop(["new title"],axis=1)

In [25]:
data["simple title"]=data["Title"].apply(lambda i:gensim.utils.simple_preprocess(i))

In [26]:
data

,Title,simple title
0,Obama Lays Wreath at Arlington National Cemetery,"[obama, lays, wreath, at, arlington, national, cemetery]"
1,A Look at the Health of the Chinese Economy,"[look, at, the, health, of, the, chinese, economy]"
2,Nouriel Roubini: Global Economy Not Back to 2008,"[nouriel, roubini, global, economy, not, back, to]"
3,Finland GDP Expands In Q4,"[finland, gdp, expands, in]"
4,"Tourism, govt spending buoys Thai economy in January","[tourism, govt, spending, buoys, thai, economy, in, january]"
...,...,...
55927,Fidel Castro Lashes Out at Obama After Cuba Visit,"[fidel, castro, lashes, out, at, obama, after, cuba, visit]"
55928,JOHN CRISP | Obama's strategic reaction to Brussels,"[john, crisp, obama, strategic, reaction, to, brussels]"
55929,Think Trump's 45 Percent Tariffs Are Bad? Try Obama's 10000 ...,"[think, trump, percent, tariffs, are, bad, try, obama]"
55930,Microsoft finally releases giant Surface,"[microsoft, finally, releases, giant, surface]"
55931,Rays of sunshine in the US economy,"[rays, of, sunshine, in, the, us, economy]"

In [27]:
# x=data["simple title"]

In [29]:
# x

In [33]:
# tagging
tagged_document=[]
for i,v in enumerate(data["simple title"]):
    tagged_document.append(gensim.models.doc2vec.TaggedDocument(v,[i]))

In [35]:
# tagged_document

In [37]:
model=gensim.models.Doc2Vec(tagged_document,window=5,vector_size=100,min_count=2)

In [39]:
print(model)

Doc2Vec<dm/m,d100,n5,w5,mc2,s0.001,t3>

In [45]:
model.save("doc2vec1.model")

In [43]:
a=model.infer_vector("Listening,  Reading and Writing (L-S-R-W) are the four skills of language learning".split())

In [44]:
a

array([-5.6573395e-03, -3.2722428e-02,  3.2604672e-02,  2.3158951e-02,
        4.6317617e-04,  7.3029064e-02, -2.2108207e-02,  1.1796418e-02,
        2.3505252e-02,  3.5261154e-02,  2.5968312e-03, -5.5702027e-02,
        3.2854207e-02, -4.6773586e-02, -2.5443742e-02,  1.6011797e-02,
        2.9816523e-02, -9.2593702e-03, -2.4657324e-03, -9.4390195e-03,
        2.2087665e-02, -1.8899688e-02, -6.9493167e-02,  2.0593256e-02,
       -2.8870435e-02, -2.5203967e-02,  1.6662331e-02, -4.3415654e-02,
       -3.1255481e-03, -3.9591126e-02, -2.1733595e-02,  4.0062465e-02,
       -1.1438951e-01,  1.6773468e-02, -5.1889964e-03,  2.4668682e-02,
       -2.8016701e-02, -7.8754099e-03, -5.9189696e-02,  3.9526831e-02,
        1.2055530e-02,  7.4653290e-02,  1.4248365e-02, -9.2773475e-02,
        8.8789677e-03, -8.4389346e-03,  5.9408408e-02,  1.6723268e-02,
        1.4054850e-02,  2.3008125e-04,  1.9344386e-02,  1.5714604e-02,
        8.5890062e-02, -5.9337471e-02,  6.2917280e-03, -5.8984306e-02,
       -1.7526627e-02,  8.2885504e-02,  1.3514690e-02, -3.5982545e-02,
       -2.9097700e-02, -1.4521327e-02, -1.0151312e-02, -3.3923540e-02,
        1.1489968e-03, -1.8598137e-02, -1.7624360e-02,  1.3672300e-02,
       -8.6893082e-02, -5.2438346e-03, -5.7463101e-03, -1.2104429e-02,
        1.3895246e-02, -5.3989060e-02, -1.1941598e-02,  2.3606455e-02,
        4.2099790e-03,  3.6775973e-02, -1.0532664e-02, -1.6869057e-02,
       -2.5457079e-02,  5.7210615e-03, -7.5625077e-02,  4.1749645e-05,
       -3.5607170e-02, -5.4446310e-02,  4.5850258e-02,  2.2528715e-02,
       -1.8461548e-02,  2.1166375e-02, -3.0665366e-02, -6.4224571e-02,
        2.6151119e-02, -2.2403045e-02, -1.2000613e-03, -7.1167415e-03,
        3.4679983e-02,  3.4538984e-02,  8.1252582e-02, -3.6771126e-02],
      dtype=float32)

In [ ]:
## Train doc2vec model
# model = Doc2Vec(tagged_data, vector_size=20, window=2, min_count=1, workers=4, epochs = 100)
# Save trained doc2vec model
# model.save("test_doc2vec.model")
## Load saved doc2vec model
# model= Doc2Vec.load("test_doc2vec.model")
## Print model vocabulary
# model.wv.vocab